services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    env_file:
      - ./apps/auth/.env
    ports:
      - '3000:3000'
  user:
    build:
      context: .
      dockerfile: apps/user/Dockerfile
    env_file:
      - ./apps/user/.env
    ports:
      - '3001:3001'
  products:
    build:
      context: .
      dockerfile: apps/products/Dockerfile
    env_file:
      - ./apps/products/.env
    ports:
      - '3002:3002'
  category:
    build:
     context: .
     dockerfile: apps/category/Dockerfile
    env_file:
      - ./apps/category/.env
    ports:
      - '3003:3003'